name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: List target directory
      run: ls -la $GITHUB_WORKSPACE/server/target/
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        retention-days: 2
        if-no-files-found: error
        name: server
        path: |
          ${{ github.workspace }}/target/*.jar

  build_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: | 
    - name: Use Node.js 22.9
      uses: actions/setup-node@v4
      with:
        node-version: 22.9
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: | 
        npm i
        npx run build
