name: Build Project
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List target directory
      run: ls -la target/
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar
        retention-days: 2
        if-no-files-found: warn
        path: target/*.jar

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.9
      uses: actions/setup-node@v4
      with:
        node-version: 22.9
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies and build
      env:
        CI: false  # This disables treating warnings as errors
      run: |
        npm i
        npm run build
    - name: List build directory
      run: ls -la
    - name: Upload React build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        retention-days: 2
        if-no-files-found: warn
        path: build  # Assuming your build output is in the 'build' directory
